d2/rails/helpers/config/routes.rb
Helpers::Application.routes.draw do
  root :to => 'home#home'
  get '/numbers' => 'home#numbers'
  get '/texty' => 'home#text', :as => 'text'
  get '/assets' => 'home#assets'
  get '/url' => 'home#url'
end

d2/rails/helpers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

d2/rails/helpers/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def home
	end

	def numbers
		@amount = 234
		@large_number = 8234
		@phone = 2127663665
	end

	def text
	@numbers = (1..20).to_a
	@person_count1 = 1
	@person_count2 = 2
	@story = "A very long long time ago in a place not so far, far, away"
	end

	def assets
	end

	def url
	end
end

d2/rails/helpers/app/helpers/application_helper.rb
module ApplicationHelper
end

d2/rails/helpers/app/views/home/assets.html.erb
<p>Here is the Rails Logo</p>

<%= image_tag('rails.png', :class =>'img-rounded') %>

d2/rails/helpers/app/views/home/home.html.erb
GDAY HUI NOT SURE IF I WANT TO RUN.....

d2/rails/helpers/app/views/home/numbers.html.erb
<p> The stock price is <%= number_to_currency(@amount) %> </p>
<p> This large number is <%= number_to_human(@large_number) %></p>
<p> The phone number is <%= number_to_phone(@phone, :area_code => true) %> </p>		

d2/rails/helpers/app/views/home/text.html.erb
<p> There are <%= pluralize(@person_count1, 'person') %> signed up. </p>
<p> There are <%= pluralize(@person_count2, 'cow') %> waiting. </p>

<p><%= truncate(@story, :length => 15) %></p>
<ul>
	<% @numbers.each do |num| %>
	<li style= "background-color:<%= cycle('red', 'green', 'orange', 'purple') %>">Number <%= num %> </li>
	<% end %>
</ul>

d2/rails/helpers/app/views/home/url.html.erb
<%=link_to('Home',',') %>

<a href='/text'>Text</a>
<%= link_to('Text', text_path) %>

<%= button_to('Submit to me', '/test') %>

nav>ul>li.someclass*3>a

<nav>
	<ul>
		<li><a href=""></a></li>
		<li><a href=""></a></li>
		<li><a href=""></a></li></ul></nav>