d2/planets/config/routes.rb
Planets::Application.routes.draw do
	
root  :to => 'planets#index'

get '/planets' => 'planets#index'
post '/planets' => 'planets#create'
get '/planets/new'  => 'planets#new'

get '/planets/:id' => 'planets#show', :as => 'planet'
post '/planets/:id/delete' => 'planets#destroy', 	:as => 'planet_delete'

get '/planets/:id/edit' => 'planets#edit', :as => 'planet_edit'
post '/planets/:id' => 'planets#update'
end

d2/planets/app/models/planet.rb
# == Schema Information
#
# Table name: planets
#
#  id       :integer          not null, primary key
#  name     :string(255)
#  image    :text
#  orbit    :float
#  diameter :float
#  mass     :float
#  moons    :integer
#

class Planet < ActiveRecord::Base
attr_accessible :name, :image, :orbit, :diameter, :mass, :moons
end

d2/planets/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

d2/planets/app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
		def index
		@planets = Planet.all
		end
		def new
		end
		def create
		Planet.create(params[:planet])
		redirect_to(planets_path)
		end
		def show
		@planet = Planet.find(params[:id])
		end

		def destroy
			planet = Planet.find(params[:id])
			planet.destroy
			redirect_to(planets_path)
		end

		def edit
		@planet = Planet.find(params[:id])

		def update
		planet = Planet.find(params[:id])
		planet.update_attributes(params[:planet])
		redirect_to(planets_path)
	end
	end

end

d2/planets/app/helpers/application_helper.rb
module ApplicationHelper
end

d2/planets/app/views/planets/edit.html.erb
<form method ="post" action="<%= planet_path(@planet.id) %>
	<input type="text" name="planet[name]" autofocus placeholder="name" value="<%=@planet.name %">
	<input type="text" name="planet[orbit]" value="<%=@planet.orbit %">
	<input type="text" name="planet[diameter]" value="<%=@planet.diameter %">
	<input type="text" name="planet[mass]" value="<%= @planet.mass %">
	<input type="text" name="planet[moons]" value="<%= planet.moons %">
	<button>PLANET ME</button>
</form>

d2/planets/app/views/planets/index.html.erb
<% @planets.each do |planet| %>
<p><%= link_to(planet.name, planet_path(planet.id))	 %> has <%=pluralize(planet.moons, 'moon') %>. </p>

<%= link_to ('Edit Planet'), planet_edit_path(planet.id) %>
<%= button_to('Delete Planet', planet_delete_path(planet.id)) %>
</p>
<% end %>

d2/planets/app/views/planets/new.html.erb
<form method ="post" action="/planets">
	<input type="text" name="planet[name]" autofocus placeholder="name">
	<input type="text" name="planet[orbit]">
	<input type="text" name="planet[diameter]">
	<input type="text" name="planet[mass]">
	<input type="text" name="planet[moons]">
	<button>PLANET ME</button>
</form>

d2/planets/app/views/planets/show.html.erb
YOU ARE LOOKING AT <%= @mountain.name %> which has an average orbit of <%= @mountain.orbit %> AUs