d3/moma/config/routes.rb
Moma::Application.routes.draw do
  resources :artists, :paintings
end

d3/moma/app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  nationality :string(255)
#  dob         :date
#  period      :string(255)
#  image       :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class AddArtistIdToPaintingsTable < ActiveRecord::Migration
	def change
		add_column :paintings :artist_id, :integer
end
# 	Artist < ActiveRecord::Base
# 	attr_accessible :name, :nationality, :dob, :period, :image
# 	has_many	:paintings
# end

d3/moma/app/models/painting.rb
# == Schema Information
#
# Table name: paintings
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  medium     :date
#  style      :string(255)
#  image      :text
#  year       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Painting < ActiveRecord::Base
	attr_accessible :medium, :style, :year, :image, :title
	belongs_to :artist
end	

d3/moma/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

d3/moma/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	def index
	@artists	= Artist.all
	end	

	def new
		@artist = Artist.new
	end

	def create
		artist = Artist.create(params[:artist])
		redirect_to(artist)
		# raise params.inspect
	end

	def show
		@artist = Artist.find(params[:id])
	end

	def edit
		@artist = Artist.find(params[:id])

	end

	def update
	artist = Artist.find(params[:id])
	artist.update_attributes(params[:artist])
	redirect_to(artist)
	end

	def destroy
		artist = Artist.find(params[:id])
		artist.destroy
	end
end

d3/moma/app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
	def index
		@paintings = Painting.all
	end

	def new
		@painting = Painting.new
	end

	def create
		painting = Painting.create(params[:painting])
		redirect_to(artist)
	end

	def show
		@painting = Painting.find(params[:id])
	end

	def edit
		@painting = Painting.new
	end

	def update
	painting = Painting.find(params[:id])
	painting.update_attributes(params[:painting])
	redirect_to(painting)
	end

	def destroy
		@painting = Painting.find(params[:id])
		painting.destroy
		redirect_to(paintings_path)
	end
end

d3/moma/app/helpers/application_helper.rb
module ApplicationHelper
end

d3/moma/app/views/artists/_form.html.erb
<%= form_for @artists do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<br>
<%= f.label :nationality %>
<%= f.text_field :nationality %>
<br>
<%= f.label :dob %>
<%= f.text_field :dob %>
<br>
<%= f.label :period %>
<%= f.text_field :period %>
<br>
<%= f.label :image %>
<%= f.text_field :image %>
<br>
<%= f.submit %>
<% end %>

<!-- need to correct fields for painting -->

d3/moma/app/views/artists/edit.html.erb
<h1>Edit Artist</h1>
<%= render	:partial => 'form' %>

d3/moma/app/views/artists/index.html.erb
<% @artists.each do |artist| %>
<ul>
<!-- <li><%= image_tag(artist.image) %></li>
 -->
 <li>
 <%= link_to(artist.name, artist_path(artist.id))%>
 </li>
  <li>
 <%= link_to(artist.name, artist)%>
 </li>
<!-- <li><%= artist.nationality %></li>
<li><%= artist.dob.strftime('%B %d %Y') %></li>
<li><%= artist.period %></li>
 --></ul>
<% end %>

d3/moma/app/views/artists/new.html.erb
<h1>New Artist</h1>
<%= render	:partial => 'form' %>

d3/moma/app/views/artists/show.html.erb
<%= @artist %>

<%= link_to 'delete', @artist, :method => :delete %>

<%= link_to 'edit', edit_artist_path(@artist) %>